apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: LoadBalancer 
  ports:
    - name: http
      port: 80
  ports:
    - name: mongo
      port: 27017
  selector:
    app: application
