apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  selector:
    matchLabels:
      app: application
  replicas: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: apigateway
        image: evaughan00/mlhub-api-gateway:1.2
        ports:
        - containerPort: 80
