apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: apigateway
        image: evaughan00/mlhub-api-gateway:1.3
        ports:
        - containerPort: 8080
      - name: frontend
        image: evaughan00/mlhub-frontend:1.1
        ports:
        - containerPort: 80
